<?php

session_start();

$name=$_POST['name'];
$email=$_POST['email'];
$comp=$_POST['comp'];
$memb=$_POST['memb'];

  if($comp == "") 
  {
    $_SESSION['entry'] = 'nocomp';
    header($_SESSION['page']);
  }
  else if($memb == "") 
  {
    $_SESSION['entry'] = 'nomemb';
    header($_SESSION['page']);
  } 
  else
  {

    $to = "leagues@hgsrc.co.uk";
$subject = "STST 2014 Entry (generated by web site form)";
$message = "NAME: ".$name."\n\nEMAIL: ".$email."\n\nMEMBER TYPE:".$memb."\n\nWANTS TO ENTER: ".$comp;
$from = $email;
$headers = "From:" . $from;
mail($to,$subject,$message,$headers);

$_SESSION['entry'] = 'sent';

header($_SESSION['page']);


  }




?>